version: "3.1"
services:

    db:
      image: mysql:8.0
      container_name: mysql
      working_dir: /app
      volumes:
        - .:/app
      environment:
        - MYSQL_ROOT_PASSWORD=root_pass
        - MYSQL_DATABASE=base
        - MYSQL_USER=base_user
        - MYSQL_PASSWORD=user_pass
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /app
      volumes:
          - .:/app
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: php-fpm
      working_dir: /app
      volumes:
        - .:/app
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

